export const GAME_CONSTANTS = {
  GRID_SIZE: 3,
  VISION_FRAME_SIZE: 2,
  CELL_SIZE: 110,
  CELL_GAP: 4,

  HERO_INITIAL_POWER: 10,

  IMP_HP: 3,
  IMP_ATTACK: 1,

  DRAGON_BASE_COMBAT_POWER: 20,
  DRAGON_BASE_ATTACK: 3,

  SCREEN_WIDTH: 960,
  SCREEN_HEIGHT: 720,
};
