// This file is generated by tools/generate-data.mjs. Do not edit by hand.

export const GENERATED_DRAGON_DATA = [
  {
    "id": "wyvern",
    "name": "亚龙",
    "personality": "wyvern",
    "breathRange": 1,
    "color": 6728294,
    "unlockTurn": 1,
    "spawnWeight": 4,
    "quantity": 3,
    "description": "受伤后在本回合战斗结算完离开",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 15
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 21
      },
      {
        "round": 3,
        "attack": 13,
        "hp": 33
      },
      {
        "round": 4,
        "attack": 20,
        "hp": 57
      },
      {
        "round": 5,
        "attack": 30,
        "hp": 90
      },
      {
        "round": 6,
        "attack": 45,
        "hp": 144
      }
    ]
  },
  {
    "id": "aurus",
    "name": "黄金龙",
    "personality": "gold",
    "breathRange": 1,
    "color": 16763904,
    "unlockTurn": 2,
    "spawnWeight": 3,
    "quantity": 2,
    "description": "吐息命中空地或击破建筑/单位后若扇区为空则生成金矿",
    "growth": [
      {
        "round": 1,
        "attack": 7,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 10,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 15,
        "hp": 66
      },
      {
        "round": 4,
        "attack": 22,
        "hp": 114
      },
      {
        "round": 5,
        "attack": 32,
        "hp": 180
      },
      {
        "round": 6,
        "attack": 47,
        "hp": 288
      }
    ]
  },
  {
    "id": "furo",
    "name": "破坏龙",
    "personality": "destructive",
    "breathRange": 3,
    "color": 8930508,
    "unlockTurn": 4,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "击破地块后顺时针移动 1 边并继续攻击",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 10,
        "hp": 60
      },
      {
        "round": 4,
        "attack": 13,
        "hp": 75
      },
      {
        "round": 5,
        "attack": 16,
        "hp": 100
      },
      {
        "round": 6,
        "attack": 23,
        "hp": 130
      }
    ]
  },
  {
    "id": "ignis",
    "name": "高傲龙",
    "personality": "arrogant",
    "breathRange": 3,
    "color": 16729156,
    "unlockTurn": 6,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "生成和击破目标后选择攻击最高友方所在扇区附近；每次攻击后 +5 攻击",
    "growth": [
      {
        "round": 1,
        "attack": 3,
        "hp": 20
      },
      {
        "round": 2,
        "attack": 5,
        "hp": 30
      },
      {
        "round": 3,
        "attack": 8,
        "hp": 45
      },
      {
        "round": 4,
        "attack": 13,
        "hp": 60
      },
      {
        "round": 5,
        "attack": 18,
        "hp": 100
      },
      {
        "round": 6,
        "attack": 25,
        "hp": 150
      }
    ]
  },
  {
    "id": "gulo",
    "name": "贪食龙",
    "personality": "gluttonous",
    "breathRange": 3,
    "color": 16746564,
    "unlockTurn": 10,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "攻击后吞噬最近白天区域其他龙，获得其 HP 和攻击；攻击 2 次后离开",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 13,
        "hp": 66
      },
      {
        "round": 4,
        "attack": 18,
        "hp": 114
      },
      {
        "round": 5,
        "attack": 30,
        "hp": 180
      },
      {
        "round": 6,
        "attack": 40,
        "hp": 288
      }
    ]
  },
  {
    "id": "brutus",
    "name": "火龙",
    "personality": "brutal",
    "breathRange": 1,
    "color": 13378082,
    "unlockTurn": 10,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "攻击结算后在范围空地生成 10 HP 龙焰",
    "growth": [
      {
        "round": 1,
        "attack": 10,
        "hp": 50
      },
      {
        "round": 2,
        "attack": 13,
        "hp": 70
      },
      {
        "round": 3,
        "attack": 18,
        "hp": 110
      },
      {
        "round": 4,
        "attack": 25,
        "hp": 190
      },
      {
        "round": 5,
        "attack": 35,
        "hp": 300
      },
      {
        "round": 6,
        "attack": 50,
        "hp": 480
      }
    ]
  }
] as const;

export const GENERATED_ITEM_DATA = [
  {
    "id": "block:wood_wall",
    "kind": "block",
    "blockType": "wood_wall",
    "spellType": "",
    "label": "木墙",
    "cost": 5,
    "hp": 8,
    "attack": 0,
    "color": 9136404,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础"
    ],
    "description": [
      "8 HP",
      "0 攻击力",
      "阻挡吐息"
    ]
  },
  {
    "id": "block:mine",
    "kind": "block",
    "blockType": "mine",
    "spellType": "",
    "label": "矿场",
    "cost": 15,
    "hp": 8,
    "attack": 0,
    "color": 8947797,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础"
    ],
    "description": [
      "每回合获得 4 金币"
    ]
  },
  {
    "id": "spell:missile",
    "kind": "spell",
    "blockType": "",
    "spellType": "missile",
    "label": "飞弹",
    "cost": 10,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础",
      "法术"
    ],
    "description": [
      "对选择目标造成 5 点伤害"
    ]
  },
  {
    "id": "block:ballista",
    "kind": "block",
    "blockType": "ballista",
    "spellType": "",
    "label": "巨弩",
    "cost": 10,
    "hp": 8,
    "attack": 5,
    "color": 8947848,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每回合若未攻击，+5 临时攻击力",
      "攻击后移除已积累的临时攻击力"
    ]
  },
  {
    "id": "block:pressure_stone",
    "kind": "block",
    "blockType": "pressure_stone",
    "spellType": "",
    "label": "压力石",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 6702250,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "放置时获得本扇区及左右相邻扇区所有龙当前 HP 总和的 1/4（向下取整）"
    ]
  },
  {
    "id": "block:guardian",
    "kind": "block",
    "blockType": "guardian",
    "spellType": "",
    "label": "卫士",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 16768426,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "攻击力始终与 HP 相同"
    ]
  },
  {
    "id": "block:portal",
    "kind": "block",
    "blockType": "portal",
    "spellType": "",
    "label": "通道",
    "cost": 20,
    "hp": 30,
    "attack": 0,
    "color": 8930508,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "被吐息命中时，对侧扇区可攻击友方会反击该龙",
      "自身受到伤害正常计算"
    ]
  },
  {
    "id": "block:spikes",
    "kind": "block",
    "blockType": "spikes",
    "spellType": "",
    "label": "地刺",
    "cost": 10,
    "hp": 15,
    "attack": 2,
    "color": 11184810,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "有任意龙进入/离开此扇区时，地刺也会攻击它"
    ]
  },
  {
    "id": "block:tavern",
    "kind": "block",
    "blockType": "tavern",
    "spellType": "",
    "label": "酒馆",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 13404228,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "白天每回合 +2 金币",
      "黑夜每回合 +6 金币"
    ]
  },
  {
    "id": "block:smithy",
    "kind": "block",
    "blockType": "smithy",
    "spellType": "",
    "label": "铁匠铺",
    "cost": 25,
    "hp": 10,
    "attack": 1,
    "color": 11036722,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "相邻扇区放置建筑/单位时，使其获得铁匠铺当前攻击力，并使铁匠铺 +1 攻击力"
    ]
  },
  {
    "id": "block:assassin",
    "kind": "block",
    "blockType": "assassin",
    "spellType": "",
    "label": "刺客",
    "cost": 10,
    "hp": 8,
    "attack": 0,
    "color": 3355443,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "黑夜时 +35 攻击力",
      "攻击 1 次后销毁自身"
    ]
  },
  {
    "id": "block:bellows",
    "kind": "block",
    "blockType": "bellows",
    "spellType": "",
    "label": "风箱",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 7838122,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "受击后，将攻击者沿顺时针方向逐格移动 3 格"
    ]
  },
  {
    "id": "block:sensing_wall",
    "kind": "block",
    "blockType": "sensing_wall",
    "spellType": "",
    "label": "感应石墙",
    "cost": 30,
    "hp": 40,
    "attack": 0,
    "color": 4892330,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "任意空地即将被攻击时，自动移动到该空地抵挡",
      "最多只能同时存在 1 个"
    ]
  },
  {
    "id": "block:dragon_spear",
    "kind": "block",
    "blockType": "dragon_spear",
    "spellType": "",
    "label": "龙枪",
    "cost": 30,
    "hp": 15,
    "attack": 5,
    "color": 12074030,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每次攻击前，每有 1 个空地获得 10 临时攻击力",
      "若攻击击杀任意龙，本轮剩余龙行动全部跳过"
    ]
  },
  {
    "id": "block:knight",
    "kind": "block",
    "blockType": "knight",
    "spellType": "",
    "label": "骑士",
    "cost": 25,
    "hp": 20,
    "attack": 10,
    "color": 4491519,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每次攻击前，本回合每旋转 1 扇区获得 +2/+2（临时）"
    ]
  },
  {
    "id": "block:mage",
    "kind": "block",
    "blockType": "mage",
    "spellType": "",
    "label": "法师",
    "cost": 40,
    "hp": 8,
    "attack": 1,
    "color": 11158783,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每回合使商店中的飞弹+2临时攻击力。"
    ]
  },
  {
    "id": "block:wizard",
    "kind": "block",
    "blockType": "wizard",
    "spellType": "",
    "label": "巫师",
    "cost": 25,
    "hp": 8,
    "attack": 0,
    "color": 7031746,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "若放置的扇区中有龙，在临时槽生成 1 张 5 金币的【驱离】",
      "驱离只能影响生成时绑定类型的龙"
    ]
  },
  {
    "id": "block:infantry",
    "kind": "block",
    "blockType": "infantry",
    "spellType": "",
    "label": "步兵",
    "cost": 15,
    "hp": 10,
    "attack": 5,
    "color": 5213274,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "两边相邻扇区的友方攻击时，自身也对其目标攻击 1 次"
    ]
  },
  {
    "id": "block:scout",
    "kind": "block",
    "blockType": "scout",
    "spellType": "",
    "label": "斥候",
    "cost": 25,
    "hp": 0,
    "attack": 10,
    "color": 6987976,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "放置后获得左右相邻扇区各一半 HP（向下取整）",
      "下一条新出现的龙必定出现在此扇区"
    ]
  },
  {
    "id": "spell:focus_defense",
    "kind": "spell",
    "blockType": "",
    "spellType": "focus_defense",
    "label": "集中防御",
    "cost": 20,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "指定友方，吸收左右相邻友方各一半 HP"
    ]
  },
  {
    "id": "spell:focus_breakthrough",
    "kind": "spell",
    "blockType": "",
    "spellType": "focus_breakthrough",
    "label": "集中突破",
    "cost": 25,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "指定友方，吸收左右相邻友方各一半攻击力"
    ]
  },
  {
    "id": "spell:sacrifice",
    "kind": "spell",
    "blockType": "",
    "spellType": "sacrifice",
    "label": "献祭",
    "cost": 20,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "摧毁指定友方，将其一半 HP/攻击传递给随机友方"
    ]
  },
  {
    "id": "spell:bulwark",
    "kind": "spell",
    "blockType": "",
    "spellType": "bulwark",
    "label": "壁垒",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "所有攻击力为 0 的友方 +5 HP"
    ]
  },
  {
    "id": "spell:shield_crush",
    "kind": "spell",
    "blockType": "",
    "spellType": "shield_crush",
    "label": "盾牌碾压",
    "cost": 25,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "摧毁攻击力为 0 的友方，对其扇区敌人造成其 HP 的伤害"
    ]
  },
  {
    "id": "spell:apple",
    "kind": "spell",
    "blockType": "",
    "spellType": "apple",
    "label": "苹果",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 14241597,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "使 1 个友方建筑/单位永久获得 +3/+3"
    ]
  },
  {
    "id": "block:ghost",
    "kind": "block",
    "blockType": "ghost",
    "spellType": "",
    "label": "幽灵",
    "cost": 20,
    "hp": 15,
    "attack": 5,
    "color": 12572671,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "在黑夜区域时，具有亡语：在此扇区召唤 1 只 1 HP 幽灵，并获得自身攻击"
    ]
  },
  {
    "id": "block:goblin",
    "kind": "block",
    "blockType": "goblin",
    "spellType": "",
    "label": "地精",
    "cost": 15,
    "hp": 15,
    "attack": 8,
    "color": 8044367,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "放置后：你购买的下一个商品金币消耗 -10"
    ]
  },
  {
    "id": "block:priest",
    "kind": "block",
    "blockType": "priest",
    "spellType": "",
    "label": "牧师",
    "cost": 30,
    "hp": 20,
    "attack": 3,
    "color": 16180904,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "在白天区域时，每回合使村庄获得 3 点治疗"
    ]
  },
  {
    "id": "block:market",
    "kind": "block",
    "blockType": "market",
    "spellType": "",
    "label": "市场",
    "cost": 20,
    "hp": 25,
    "attack": 0,
    "color": 14721882,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每回合可以免费刷新 1 次"
    ]
  },
  {
    "id": "spell:magic_book",
    "kind": "spell",
    "blockType": "",
    "spellType": "magic_book",
    "label": "魔法书",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 8308991,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "购买后，获得 2 张临时的随机法术"
    ]
  },
  {
    "id": "spell:repel",
    "kind": "spell",
    "blockType": "",
    "spellType": "repel",
    "label": "驱离",
    "cost": 0,
    "hp": 0,
    "attack": 0,
    "color": 10940671,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [
      "法术"
    ],
    "description": [
      "驱赶与生成时绑定类型相同的龙，使其离开"
    ]
  },
  {
    "id": "block:power_stone",
    "kind": "block",
    "blockType": "power_stone",
    "spellType": "",
    "label": "金矿",
    "cost": 0,
    "hp": 5,
    "attack": 0,
    "color": 16755200,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "生成时随机获得 1-20 HP",
      "受击时获得损失 HP 等量金币"
    ]
  },
  {
    "id": "block:voodoo",
    "kind": "block",
    "blockType": "voodoo",
    "spellType": "",
    "label": "巫毒娃娃",
    "cost": 0,
    "hp": 20,
    "attack": 0,
    "color": 8947848,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "每回合顺时针移动 1 格",
      "会被友方效果判定为敌人",
      "受到伤害会传递给记录目标"
    ]
  },
  {
    "id": "block:dragon_fire",
    "kind": "block",
    "blockType": "dragon_fire",
    "spellType": "",
    "label": "龙焰",
    "cost": 0,
    "hp": 10,
    "attack": 0,
    "color": 16733474,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "每回合对村庄造成等同 HP 的伤害",
      "建筑/单位放到龙焰上会改为削减龙焰 HP",
      "受到龙攻击时增加等同龙攻击力的 HP，龙攻击会穿透并伤害村庄"
    ]
  },
  {
    "id": "block:weakness",
    "kind": "block",
    "blockType": "weakness",
    "spellType": "",
    "label": "弱点",
    "cost": 0,
    "hp": 0,
    "attack": 0,
    "color": 16724787,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "暂无效果"
    ]
  }
] as const;

export const GENERATED_RELIC_DATA = [
  {
    "id": "village_heart",
    "label": "村庄之心",
    "color": 16739179,
    "iconKey": "heart",
    "maxSelections": null,
    "description": [
      "村庄生命 +50",
      "下次选择本遗物时增加值 +50"
    ]
  },
  {
    "id": "auto_missile",
    "label": "自动飞弹",
    "color": 6262227,
    "iconKey": "missile",
    "maxSelections": 1,
    "description": [
      "每回合自动向生命最高的龙发射 1 枚与飞弹属性相同的飞弹"
    ]
  },
  {
    "id": "night_shield",
    "label": "夜幕护盾",
    "color": 8359167,
    "iconKey": "shield",
    "maxSelections": 1,
    "description": [
      "每回合当前处于黑夜区域的友方建筑/单位获得护盾，抵御 1 次伤害"
    ]
  },
  {
    "id": "wood_wall_hp",
    "label": "加固木墙",
    "color": 12159546,
    "iconKey": "wall",
    "maxSelections": 1,
    "description": [
      "【木墙】HP +10，已有和未来木墙都会生效"
    ]
  },
  {
    "id": "wood_wall_death",
    "label": "爆裂木墙",
    "color": 14182970,
    "iconKey": "burst",
    "maxSelections": 1,
    "description": [
      "之后放置的【木墙】HP -5，最低为 1",
      "【木墙】亡语：对扇区内敌人造成 20 点伤害"
    ]
  },
  {
    "id": "wood_wall_night_stack",
    "label": "夜墙叠筑",
    "color": 9136404,
    "iconKey": "stack",
    "maxSelections": 1,
    "description": [
      "【木墙】可以放置在处于黑夜中的友方建筑/单位上，使其 HP 增加等同木墙 HP 的值"
    ]
  },
  {
    "id": "gold_mine_rally",
    "label": "金矿鼓舞",
    "color": 16755200,
    "iconKey": "gold",
    "maxSelections": 1,
    "description": [
      "场上每个金矿每回合使 1 个随机友军获得 +1/+1"
    ]
  },
  {
    "id": "gold_attack",
    "label": "金币激励",
    "color": 16765806,
    "iconKey": "coin_sword",
    "maxSelections": 1,
    "description": [
      "获得金币时，随机 1 个友军获得 3 点攻击"
    ]
  },
  {
    "id": "single_dragon_knight",
    "label": "决斗骑士",
    "color": 4491519,
    "iconKey": "knight",
    "maxSelections": 1,
    "description": [
      "场上只有 1 只龙时，骑士通过旋转获取的加成翻倍"
    ]
  },
  {
    "id": "pressure_gold",
    "label": "压力炼金",
    "color": 8213959,
    "iconKey": "pressure",
    "maxSelections": 1,
    "description": [
      "【压力石】放置后也会获得等同 HP 的金币"
    ]
  },
  {
    "id": "friendly_growth",
    "label": "全军操练",
    "color": 7653743,
    "iconKey": "growth",
    "maxSelections": 1,
    "description": [
      "所有友方每回合随机 +2 HP 或 +1 攻击力"
    ]
  },
  {
    "id": "missile_extra_hit",
    "label": "连发飞弹",
    "color": 7518207,
    "iconKey": "missile_plus",
    "maxSelections": 1,
    "description": [
      "飞弹的触发次数 +1"
    ]
  },
  {
    "id": "mine_attack",
    "label": "战斗矿场",
    "color": 10526816,
    "iconKey": "mine",
    "maxSelections": 1,
    "description": [
      "【矿场】攻击 +3，每回合对自身相邻的金矿进行 1 次攻击"
    ]
  },
  {
    "id": "gold_curse",
    "label": "贪婪契约",
    "color": 15779915,
    "iconKey": "curse",
    "maxSelections": 1,
    "description": [
      "每回合额外获得 40 金币",
      "若回合结束时有剩余，村庄损失 20 生命"
    ]
  },
  {
    "id": "dragon_bounty",
    "label": "屠龙赏金",
    "color": 16762967,
    "iconKey": "dragon_coin",
    "maxSelections": 1,
    "description": [
      "击杀任意龙时，村庄 +15 金币，+10 HP"
    ]
  },
  {
    "id": "infantry_legacy",
    "label": "步兵传承",
    "color": 7328908,
    "iconKey": "infantry",
    "maxSelections": 1,
    "description": [
      "每次放置【步兵】时，使其获得当前传承值的 +HP/+攻击",
      "初始为 1，步兵死亡时永久提升 1 点"
    ]
  },
  {
    "id": "sell_copy",
    "label": "战术回收",
    "color": 10473727,
    "iconKey": "copy",
    "maxSelections": 1,
    "description": [
      "出售任意友方后，在临时商店生成 1 个其基础复制",
      "已有同名复制时不再生成"
    ]
  },
  {
    "id": "militia_deathrattle",
    "label": "民兵遗愿",
    "color": 13100684,
    "iconKey": "deathrattle",
    "maxSelections": 1,
    "description": [
      "所有非亡语效果的友方具有亡语：在原扇区召唤 1 个 5/5 的【步兵】"
    ]
  },
  {
    "id": "wounded_veterans",
    "label": "浴血精锐",
    "color": 15764061,
    "iconKey": "veteran",
    "maxSelections": 1,
    "description": [
      "【骑士】【步兵】【斥候】受伤后若存活，永久 +2 攻击"
    ]
  }
] as const;
