// This file is generated by tools/generate-data.mjs. Do not edit by hand.

export const GENERATED_DRAGON_DATA = [
  {
    "id": "wyvern",
    "name": "亚龙",
    "personality": "wyvern",
    "breathRange": 1,
    "color": 6728294,
    "unlockTurn": 1,
    "spawnWeight": 4,
    "quantity": 3,
    "description": "受伤后离开",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 15
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 21
      },
      {
        "round": 3,
        "attack": 13,
        "hp": 33
      },
      {
        "round": 4,
        "attack": 20,
        "hp": 57
      },
      {
        "round": 5,
        "attack": 30,
        "hp": 90
      },
      {
        "round": 6,
        "attack": 45,
        "hp": 144
      }
    ]
  },
  {
    "id": "aurus",
    "name": "奥鲁斯",
    "personality": "gold",
    "breathRange": 1,
    "color": 16763904,
    "unlockTurn": 2,
    "spawnWeight": 3,
    "quantity": 2,
    "description": "吐息命中空地并造成伤害后生成金矿",
    "growth": [
      {
        "round": 1,
        "attack": 7,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 10,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 15,
        "hp": 66
      },
      {
        "round": 4,
        "attack": 22,
        "hp": 114
      },
      {
        "round": 5,
        "attack": 32,
        "hp": 180
      },
      {
        "round": 6,
        "attack": 47,
        "hp": 288
      }
    ]
  },
  {
    "id": "furo",
    "name": "弗罗",
    "personality": "destructive",
    "breathRange": 3,
    "color": 8930508,
    "unlockTurn": 4,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "击破地块后顺时针移动 1 边并继续攻击",
    "growth": [
      {
        "round": 1,
        "attack": 10,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 13,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 18,
        "hp": 66
      },
      {
        "round": 4,
        "attack": 25,
        "hp": 114
      },
      {
        "round": 5,
        "attack": 35,
        "hp": 180
      },
      {
        "round": 6,
        "attack": 50,
        "hp": 288
      }
    ]
  },
  {
    "id": "ignis",
    "name": "伊格尼斯",
    "personality": "arrogant",
    "breathRange": 3,
    "color": 16729156,
    "unlockTurn": 6,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "生成和击破目标后选择攻击最高友方所在扇区附近；每次攻击后 +5 攻击",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 40
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 56
      },
      {
        "round": 3,
        "attack": 13,
        "hp": 88
      },
      {
        "round": 4,
        "attack": 20,
        "hp": 152
      },
      {
        "round": 5,
        "attack": 30,
        "hp": 240
      },
      {
        "round": 6,
        "attack": 45,
        "hp": 384
      }
    ]
  },
  {
    "id": "gulo",
    "name": "古洛",
    "personality": "gluttonous",
    "breathRange": 3,
    "color": 16746564,
    "unlockTurn": 10,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "攻击后吞噬最近白天区域其他龙，获得其 HP 和攻击；攻击 2 次后离开",
    "growth": [
      {
        "round": 1,
        "attack": 5,
        "hp": 30
      },
      {
        "round": 2,
        "attack": 8,
        "hp": 42
      },
      {
        "round": 3,
        "attack": 13,
        "hp": 66
      },
      {
        "round": 4,
        "attack": 18,
        "hp": 114
      },
      {
        "round": 5,
        "attack": 30,
        "hp": 180
      },
      {
        "round": 6,
        "attack": 40,
        "hp": 288
      }
    ]
  },
  {
    "id": "brutus",
    "name": "布鲁图斯",
    "personality": "brutal",
    "breathRange": 1,
    "color": 13378082,
    "unlockTurn": 10,
    "spawnWeight": 2,
    "quantity": 1,
    "description": "攻击结算后在范围空地生成 10 HP 龙焰；已有龙焰则 +10 HP",
    "growth": [
      {
        "round": 1,
        "attack": 10,
        "hp": 50
      },
      {
        "round": 2,
        "attack": 13,
        "hp": 70
      },
      {
        "round": 3,
        "attack": 18,
        "hp": 110
      },
      {
        "round": 4,
        "attack": 25,
        "hp": 190
      },
      {
        "round": 5,
        "attack": 35,
        "hp": 300
      },
      {
        "round": 6,
        "attack": 50,
        "hp": 480
      }
    ]
  }
] as const;

export const GENERATED_ITEM_DATA = [
  {
    "id": "block:wood_wall",
    "kind": "block",
    "blockType": "wood_wall",
    "spellType": "",
    "label": "木墙",
    "cost": 5,
    "hp": 8,
    "attack": 0,
    "color": 9136404,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础"
    ],
    "description": [
      "8 HP",
      "0 攻击力",
      "阻挡吐息"
    ]
  },
  {
    "id": "block:mine",
    "kind": "block",
    "blockType": "mine",
    "spellType": "",
    "label": "矿场",
    "cost": 15,
    "hp": 8,
    "attack": 0,
    "color": 8947797,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础"
    ],
    "description": [
      "每回合获得 4 金币"
    ]
  },
  {
    "id": "spell:missile",
    "kind": "spell",
    "blockType": "",
    "spellType": "missile",
    "label": "飞弹",
    "cost": 10,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": true,
    "randomShop": false,
    "tags": [
      "基础",
      "法术"
    ],
    "description": [
      "对选择目标造成 5 点伤害",
      "每个法师增加 1 次效果并附加攻击力"
    ]
  },
  {
    "id": "block:ballista",
    "kind": "block",
    "blockType": "ballista",
    "spellType": "",
    "label": "巨弩",
    "cost": 10,
    "hp": 8,
    "attack": 5,
    "color": 8947848,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每回合若未攻击，+5 临时攻击力",
      "攻击后移除已积累的临时攻击力"
    ]
  },
  {
    "id": "block:pressure_stone",
    "kind": "block",
    "blockType": "pressure_stone",
    "spellType": "",
    "label": "压力石",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 6702250,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "放置时获得本扇区及左右相邻扇区所有龙当前 HP 总和的 1/4（向下取整）"
    ]
  },
  {
    "id": "block:guardian",
    "kind": "block",
    "blockType": "guardian",
    "spellType": "",
    "label": "卫士",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 16768426,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "攻击力始终与 HP 相同"
    ]
  },
  {
    "id": "block:portal",
    "kind": "block",
    "blockType": "portal",
    "spellType": "",
    "label": "通道",
    "cost": 20,
    "hp": 30,
    "attack": 0,
    "color": 8930508,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "被吐息命中时，对侧扇区可攻击友方会反击该龙",
      "自身受到伤害正常计算"
    ]
  },
  {
    "id": "block:spikes",
    "kind": "block",
    "blockType": "spikes",
    "spellType": "",
    "label": "地刺",
    "cost": 10,
    "hp": 15,
    "attack": 2,
    "color": 11184810,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "有任意龙进入/离开此扇区时，地刺会攻击它"
    ]
  },
  {
    "id": "block:tavern",
    "kind": "block",
    "blockType": "tavern",
    "spellType": "",
    "label": "酒馆",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 13404228,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "白天每回合 +2 金币",
      "黑夜每回合 +6 金币"
    ]
  },
  {
    "id": "block:smithy",
    "kind": "block",
    "blockType": "smithy",
    "spellType": "",
    "label": "铁匠铺",
    "cost": 25,
    "hp": 10,
    "attack": 1,
    "color": 11036722,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "相邻扇区放置建筑/单位时，使其获得铁匠铺当前攻击力，并使铁匠铺 +1 攻击力"
    ]
  },
  {
    "id": "block:assassin",
    "kind": "block",
    "blockType": "assassin",
    "spellType": "",
    "label": "刺客",
    "cost": 10,
    "hp": 8,
    "attack": 0,
    "color": 3355443,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "黑夜时 +35 攻击力",
      "攻击 1 次后销毁自身"
    ]
  },
  {
    "id": "block:bellows",
    "kind": "block",
    "blockType": "bellows",
    "spellType": "",
    "label": "风箱",
    "cost": 20,
    "hp": 10,
    "attack": 0,
    "color": 7838122,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "受击后，将攻击者沿顺时针方向逐格移动 3 格"
    ]
  },
  {
    "id": "block:sensing_wall",
    "kind": "block",
    "blockType": "sensing_wall",
    "spellType": "",
    "label": "感应石墙",
    "cost": 30,
    "hp": 40,
    "attack": 0,
    "color": 4892330,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "任意空地即将被攻击时，自动移动到该空地抵挡",
      "最多只能同时存在 1 个"
    ]
  },
  {
    "id": "block:dragon_spear",
    "kind": "block",
    "blockType": "dragon_spear",
    "spellType": "",
    "label": "龙枪",
    "cost": 30,
    "hp": 15,
    "attack": 5,
    "color": 12074030,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每次攻击前，每有 1 个空地获得 10 临时攻击力",
      "若攻击击杀任意龙，本轮剩余龙行动全部跳过"
    ]
  },
  {
    "id": "block:knight",
    "kind": "block",
    "blockType": "knight",
    "spellType": "",
    "label": "骑士",
    "cost": 25,
    "hp": 20,
    "attack": 10,
    "color": 4491519,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "每次攻击前，本回合每旋转 1 扇区获得 +2/+2（临时）"
    ]
  },
  {
    "id": "block:mage",
    "kind": "block",
    "blockType": "mage",
    "spellType": "",
    "label": "法师",
    "cost": 40,
    "hp": 8,
    "attack": 1,
    "color": 11158783,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "所有法术伤害附加自身攻击力",
      "飞弹增加 1 次效果，可叠加",
      "每回合 +1 攻击力"
    ]
  },
  {
    "id": "block:wizard",
    "kind": "block",
    "blockType": "wizard",
    "spellType": "",
    "label": "巫师",
    "cost": 25,
    "hp": 8,
    "attack": 0,
    "color": 7031746,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "死亡时在随机空位召唤记录击杀者的巫毒娃娃",
      "巫毒娃娃受到的伤害也会作用于记录目标"
    ]
  },
  {
    "id": "block:infantry",
    "kind": "block",
    "blockType": "infantry",
    "spellType": "",
    "label": "步兵",
    "cost": 15,
    "hp": 10,
    "attack": 5,
    "color": 5213274,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机"
    ],
    "description": [
      "两边相邻扇区的友方攻击时，自身也对其目标攻击 1 次"
    ]
  },
  {
    "id": "spell:focus_defense",
    "kind": "spell",
    "blockType": "",
    "spellType": "focus_defense",
    "label": "集中防御",
    "cost": 20,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "指定友方，吸收左右相邻友方各一半 HP"
    ]
  },
  {
    "id": "spell:focus_breakthrough",
    "kind": "spell",
    "blockType": "",
    "spellType": "focus_breakthrough",
    "label": "集中突破",
    "cost": 25,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "指定友方，吸收左右相邻友方各一半攻击力"
    ]
  },
  {
    "id": "spell:sacrifice",
    "kind": "spell",
    "blockType": "",
    "spellType": "sacrifice",
    "label": "献祭",
    "cost": 20,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "摧毁指定友方，将其一半 HP/攻击传递给随机友方"
    ]
  },
  {
    "id": "spell:bulwark",
    "kind": "spell",
    "blockType": "",
    "spellType": "bulwark",
    "label": "壁垒",
    "cost": 15,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "所有攻击力为 0 的友方 +5 HP"
    ]
  },
  {
    "id": "spell:shield_crush",
    "kind": "spell",
    "blockType": "",
    "spellType": "shield_crush",
    "label": "盾牌碾压",
    "cost": 25,
    "hp": 0,
    "attack": 0,
    "color": 6262227,
    "purchasable": true,
    "baseShop": false,
    "randomShop": true,
    "tags": [
      "随机",
      "法术"
    ],
    "description": [
      "摧毁攻击力为 0 的友方，对其扇区敌人造成其 HP 的伤害"
    ]
  },
  {
    "id": "block:power_stone",
    "kind": "block",
    "blockType": "power_stone",
    "spellType": "",
    "label": "金矿",
    "cost": 0,
    "hp": 5,
    "attack": 0,
    "color": 16755200,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "生成时随机获得 1-20 HP",
      "受击时获得损失 HP 等量金币"
    ]
  },
  {
    "id": "block:voodoo",
    "kind": "block",
    "blockType": "voodoo",
    "spellType": "",
    "label": "巫毒娃娃",
    "cost": 0,
    "hp": 20,
    "attack": 0,
    "color": 8947848,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "每回合顺时针移动 1 格",
      "会被友方效果判定为敌人",
      "受到伤害会传递给记录目标"
    ]
  },
  {
    "id": "block:dragon_fire",
    "kind": "block",
    "blockType": "dragon_fire",
    "spellType": "",
    "label": "龙焰",
    "cost": 0,
    "hp": 10,
    "attack": 0,
    "color": 16733474,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "每回合对村庄造成等同 HP 的伤害",
      "建筑/单位放到龙焰上会改为削减龙焰 HP"
    ]
  },
  {
    "id": "block:weakness",
    "kind": "block",
    "blockType": "weakness",
    "spellType": "",
    "label": "弱点",
    "cost": 0,
    "hp": 0,
    "attack": 0,
    "color": 16724787,
    "purchasable": false,
    "baseShop": false,
    "randomShop": false,
    "tags": [],
    "description": [
      "暂无效果"
    ]
  }
] as const;
