import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(rootDir, 'src', 'config', 'generatedData.ts');

const dragons = parseCsv(await readFile(resolve(rootDir, 'data', 'dragons.csv'), 'utf8')).map(row => ({
  id: required(row, 'id'),
  name: required(row, 'name'),
  personality: required(row, 'personality'),
  breathRange: numberField(row, 'breathRange'),
  color: colorField(row, 'color'),
  unlockTurn: numberField(row, 'unlockTurn'),
  spawnWeight: numberField(row, 'spawnWeight'),
  quantity: numberField(row, 'quantity'),
  description: required(row, 'description'),
  growth: [1, 2, 3, 4, 5, 6].map(round => ({
    round,
    attack: numberField(row, `r${round}Attack`),
    hp: numberField(row, `r${round}Hp`),
  })),
}));

const shopItems = parseCsv(await readFile(resolve(rootDir, 'data', 'shop_items.csv'), 'utf8')).map(row => ({
  id: required(row, 'id'),
  kind: required(row, 'kind'),
  blockType: optional(row, 'blockType'),
  spellType: optional(row, 'spellType'),
  label: required(row, 'label'),
  cost: numberField(row, 'cost'),
  hp: numberField(row, 'hp'),
  attack: numberField(row, 'attack'),
  color: colorField(row, 'color'),
  purchasable: booleanField(row, 'purchasable'),
  baseShop: booleanField(row, 'baseShop'),
  randomShop: booleanField(row, 'randomShop'),
  tags: splitTags(optional(row, 'tags')),
  description: splitDescription(required(row, 'description')),
}));

const relics = parseCsv(await readFile(resolve(rootDir, 'data', 'relics.csv'), 'utf8')).map(row => ({
  id: required(row, 'id'),
  label: required(row, 'label'),
  color: colorField(row, 'color'),
  iconKey: required(row, 'iconKey'),
  maxSelections: optionalNumberField(row, 'maxSelections'),
  description: splitDescription(required(row, 'description')),
}));

const content = `// This file is generated by tools/generate-data.mjs. Do not edit by hand.

export const GENERATED_DRAGON_DATA = ${JSON.stringify(dragons, null, 2)} as const;

export const GENERATED_ITEM_DATA = ${JSON.stringify(shopItems, null, 2)} as const;

export const GENERATED_RELIC_DATA = ${JSON.stringify(relics, null, 2)} as const;
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, content, 'utf8');

function parseCsv(source) {
  const normalized = source.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n').trim();
  if (!normalized) return [];
  const rows = normalized.split('\n').map(parseCsvLine);
  const headers = rows.shift();
  if (!headers) return [];
  return rows
    .filter(row => row.some(cell => cell.trim() !== ''))
    .map((row, index) => {
      if (row.length !== headers.length) {
        throw new Error(`CSV row ${index + 2} has ${row.length} columns, expected ${headers.length}`);
      }
      return Object.fromEntries(headers.map((header, column) => [header, row[column]]));
    });
}

function parseCsvLine(line) {
  const cells = [];
  let cell = '';
  let inQuotes = false;
  for (let index = 0; index < line.length; index++) {
    const char = line[index];
    if (char === '"') {
      if (inQuotes && line[index + 1] === '"') {
        cell += '"';
        index++;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (char === ',' && !inQuotes) {
      cells.push(cell);
      cell = '';
      continue;
    }
    cell += char;
  }
  cells.push(cell);
  if (inQuotes) throw new Error(`Unclosed quote in CSV line: ${line}`);
  return cells.map(value => value.trim());
}

function required(row, key) {
  const value = optional(row, key);
  if (!value) throw new Error(`Missing required CSV field: ${key}`);
  return value;
}

function optional(row, key) {
  return row[key]?.trim() ?? '';
}

function numberField(row, key) {
  const value = Number(required(row, key));
  if (!Number.isFinite(value)) throw new Error(`Invalid number in ${key}: ${row[key]}`);
  return value;
}

function optionalNumberField(row, key) {
  const raw = optional(row, key);
  if (!raw) return null;
  const value = Number(raw);
  if (!Number.isFinite(value)) throw new Error(`Invalid number in ${key}: ${row[key]}`);
  return value;
}

function colorField(row, key) {
  const raw = required(row, key);
  const value = raw.startsWith('0x') ? Number.parseInt(raw.slice(2), 16) : Number(raw);
  if (!Number.isFinite(value)) throw new Error(`Invalid color in ${key}: ${raw}`);
  return value;
}

function booleanField(row, key) {
  const raw = required(row, key).toLowerCase();
  if (raw === 'true') return true;
  if (raw === 'false') return false;
  throw new Error(`Invalid boolean in ${key}: ${row[key]}`);
}

function splitTags(value) {
  return value ? value.split('|').map(tag => tag.trim()).filter(Boolean) : [];
}

function splitDescription(value) {
  return value.split('；').map(line => line.trim()).filter(Boolean);
}
